id: P20A78866
initial_creation_type: ocr
source_metadata:
  volumes:
    9cff05bc294041aa8eed4dee9790e9a3:
      base_file: v057.txt
      image_group_id: I1PD95902
      title: དབུ་མ་རྩ་བའི་འགྲེལ་པ་ག་ལས་འཇིགས་མེད།
      total_pages: 1605
      volume_number: 57
